### ISSUE TITLE
Failed to install role with ansible-galaxy

### ISSUE THREAD

**Issue by yabusygin** [yabusygin/ansible-role-netplan#8]
The following command fails:

```sh
ansible-galaxy role install --role-file=requirements.yml
```

The `requirements.yml` file content:

```yaml
---
roles:
  - name: netplan
    version: 0.3.1
    src: https://github.com/yabusygin/ansible-role-netplan.git
    scm: git
```

Error message:

```
[WARNING]: - netplan was NOT installed successfully: this role does not appear to have a meta/main.yml file.
```
